# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title R2SSUR_internal
#' @description
#' Run a SUR Bayesian sampler -- internal function
#' @name R2SSUR_internal
#' @param dataFile path to data file
#' @param outFilePath path to where the output is to be written
#' @param nIter number of iterations
#' @param nChains number of parallel chains to run
NULL

R2SSUR_internal <- function(dataFile, blockFile, structureGraphFile, outFilePath, nIter = 10L, burnin = 0L, nChains = 1L, method = "SUR", sparse = TRUE, gammaPrior = "hotspot", gammaSampler = "bandit", gammaInit = "MLE", mrfGFile = "", betaPrior = "independent") {
    .Call('_R2SSUR_R2SSUR_internal', PACKAGE = 'R2SSUR', dataFile, blockFile, structureGraphFile, outFilePath, nIter, burnin, nChains, method, sparse, gammaPrior, gammaSampler, gammaInit, mrfGFile, betaPrior)
}

