#' @title print a short summary the fitted model
#' @description
#' Print a short summary the fitted model generated by \code{BayesSUR()}, which is an object of class "BayesSUR".
#' @name print.BayesSUR
#' @param x an object of class "BayesSUR".
#' @param Pmax cutpoint for thresholding the marginal posterior probability of inclusion (mPIP). Default is 0.5
#' @param ... other arguments
#' 
#' @examples
#' \donttest{
#' data("example_eQTL", package = "BayesSUR")
#' hyperpar = list( a_w = 2 , b_w = 5 )
#' 
#' fit <- BayesSUR(Y = example_eQTL[["blockList"]][[1]], 
#'               X = example_eQTL[["blockList"]][[2]],
#'               data = example_eQTL[["data"]], outFilePath = "results/",
#'               nIter = 1000, nChains = 2, gammaPrior = "hotspot",
#'               hyperpar = hyperpar, tmpFolder = "tmp/" )
#' 
#' ## check output
#' # show the print information
#' print(fit)
#' }
#' 
#' @export
print.BayesSUR <- function(x, Pmax=0.5, ...){
  
  gamma <- as.matrix( read.table(paste(x$output$outFilePath,x$output$gamma,sep="")) )
  
  if(length(unlist(strsplit(deparse(x$call), ","))) <= 3){
    cat("\nCall:\n ", paste(unlist(strsplit(deparse(x$call), ",")),c(rep(",",length(unlist(strsplit(deparse(x$call), ",")))-1),""),sep="",collapse=""), "\n", sep="")
  }else{
    cat("\nCall:\n ", paste(unlist(strsplit(deparse(x$call), ","))[1:3],c(",",",",", ...)"),sep="",collapse=""), "\n", sep="")
  }
  
  cat("\nNumber of identified predictors (mPIP > ", Pmax, "): ", sum(gamma > Pmax), " of ", ncol(gamma), "x", nrow(gamma), "\n", sep="")
  cat("\nExpected log pointwise predictive density (elpd):\n", " elpd.LOO = ", elpd(x, method="LOO"), ",  elpd.WAIC = ", elpd(x, method="WAIC"), "\n\n", sep="")

}